#!/usr/bin/env bash
# Installing nginx web server
# Listening to port 80
sudo apt update -y
sudo apt installnginx -y

#Allowing firewall
sudo ufw allow 'Nginx HTTP'

#New index
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

#Start service
sudo service nginx start