#!/usr/bin/env bash
# Installing nginx web server
# Listening to port 80
sudo apt update -y
sudo apt install nginx -y

#Allowing firewall
sudo ufw allow 'Nginx HTTP'

#New index
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

#Redirection
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.google.com/ permanent;' /etc/nginx/sites-available/default

#Start service
sudo service nginx restart