#!/usr/bin/env bash
# Configure Nginx server to give error 404 page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo 'Hello World' | sudo tee /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Define Nginx Server Configuration
new_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location = /redirect_me {
        return 301 https://www.google.com/;
    }
}
"

# Update Nginx Default Configuration
echo "$new_config" | sudo tee /etc/nginx/sites-available/default

#Check if nginx is running and (re)start service
if [ "$(pgrep nginx | wc -l)" -le 0 ];
then
        sudo service nginx start
else
        sudo service nginx restart
fi;