#!/usr/bin/env bash
# configures an Ubuntu machine with nginx

apt-get update
apt-get -y install nginx
service nginx start
sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
