#!/usr/bin/env bash
# Creates file containing PID
# Handles signals

echo '$$' > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
i=1
while [ $i == 1 ]; do
    echo "To infinity and beyond"
    sleep 2
done